### ISSUE TITLE
[Wiki addition] : PLINK-formatted genotype data for computing reference LD

### ISSUE THREAD

**Issue by bpprins** [bogdanlab/focus#10]
Just perhaps worthwhile to add to the wiki that the necessary PLINK-formatted genotype data for computing reference LD as mentioned in the example (`1000G.EUR.QC.1`) can be downloaded and extracted as follows :

```
wget https://data.broadinstitute.org/alkesgroup/LDSCORE/1000G_Phase3_plinkfiles.tgz
tar -xvzf 1000G_Phase3_plinkfiles.tgz

**Comment by quattro** [comment]
Hi @bpprins , the latest wiki page details how to do this.

Thank you.

**Comment by bpprins** [comment]
Hey Nicholas, yes found it, I overlooked it I think- not very smart. Quickly closed the issue, thanks a lot again :)
