### ISSUE TITLE
R issue

### ISSUE THREAD

**Issue by Nucholas** [bogdanlab/focus#17]
Hi,

I have an issue when trying to import GTEx weights from FUSION

cannot load library '/home/R/R-3.5.1/lib/R/lib/libR.so': libRblas.so: cannot open shared object file: No such file or directory

**Comment by Nucholas** [comment]
and i have [2019-10-04 14:26:34 - ERROR] 'symbol' when importing from PrediXcan

**Comment by Anne-oxford** [comment]
Hi Nicholas,

Were you able to identify the source of the symbol error. I'm running into the same problem.

**Comment by quattro** [comment]
Hi, can you run the following command for me and past the contents here: pip freeze

**Comment by Nucholas** [comment]
Hi, here is the result of pip freeze
aiohttp==3.5.4
apt-xapian-index==0.47
asn1crypto==0.24.0
async-timeout==3.0.1
atomicwrites==1.2.1
attrs==17.4.0
Automat==0.6.0
backcall==0.1.0
beautifulsoup4==4.6.3
biopython==1.72
biothings-client==0.2.1
bitarray==0.8.3
blinker==1.4
bokeh==1.2.0
bs4==0.0.1
cachetools==3.1.1
cairocffi==0.9.0
CairoSVG==2.2.1
certifi==2018.1.18
cffi==1.12.3
chardet==3.0.4
click==6.7
cloud-init==19.2
cloudpickle==1.2.2
colorama==0.4.1
colormath==3.0.0
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.1.4
cssselect2==0.2.1
cupshelpers==1.0
cycler==0.10.0
Cython==0.29.10
dask==2.5.0
decorator==4.3.2
defer==1.0.6
defusedxml==0.5.0
Deprecated==1.2.6
dfply==0.3.3
dill==0.3.0
distro-info===0.18ubuntu0.18.04.1
docopt==0.6.2
factorial==1.0.0
fsspec==0.5.1
future==0.16.0
gcsfs==0.2.1
goatools==0.8.9
google-auth==1.6.3
google-auth-oauthlib==0.4.0
gseapy==0.9.5
h5py==2.9.0
hail==0.2.19
hickle==3.4.5
html5lib==1.0.1
httplib2==0.9.2
hurry.filesize==0.9
hyperlink==17.3.1
idna==2.6
idna-ssl==1.1.0
importlib-metadata==0.23
incremental==16.10.1
intervaltree==3.0.2
ipykernel==4.10.0
ipython==7.7.0
ipython-genutils==0.2.0
jedi==0.14.1
Jinja2==2.10
joblib==0.13.2
jsonpatch==1.16
jsonpointer==1.10
jsonschema==2.6.0
jupyter-client==5.3.1
jupyter-core==4.5.0
keyring==10.6.0
keyrings.alt==3.0
kiwisolver==1.0.1
language-selector==0.1
LDpred==1.0.6
llvmlite==0.27.0
locket==0.2.0
louvain==0.6.1
lxml==4.2.5
lzstring==1.0.4
macaroonbakery==1.1.3
Markdown==3.0
MarkupSafe==1.0
matplotlib==3.1.1
mock==3.0.5
more-itertools==4.3.0
multidict==4.5.2
multiqc==1.6
mygene==3.1.0
nest-asyncio==1.0.0
netifaces==0.10.4
networkx==2.2
nose==1.3.7
numba==0.42.0
numexpr==2.6.9
numpy==1.17.0
oauthlib==3.0.2
opencv-python==4.1.1.26
packaging==19.1
PAM==0.4.2
pandas==0.25.0
pandas-plink==2.0.2
parsimonious==0.8.1
parso==0.5.1
partd==1.0.0
patsy==0.5.0
pexpect==4.7.0
pickleshare==0.7.5
Pillow==5.3.0
plinkio==0.9.7
pluggy==0.13.0
prompt-toolkit==2.0.9
protobuf==3.0.0
ptyprocess==0.6.0
py==1.6.0
py4j==0.10.7
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycairo==1.16.2
pycparser==2.19
pycrypto==2.6.1
pycups==1.9.73
pyfocus==0.6.10
Pygments==2.4.2
pygobject==3.26.1
PyJWT==1.5.3
pymacaroons==0.13.0
PyNaCl==1.1.2
pyOpenSSL==17.5.0
pyparsing==2.2.1
PyQt5==5.13.0
PyQt5-sip==4.19.18
pyRFC3339==1.0
pysam==0.11.2.2
pysamstats==1.0.1
pyserial==3.4
pyspark==2.4.1
pytest==5.2.0
python-apt==1.6.4
python-dateutil==2.8.0
python-debian==0.1.32
python-igraph==0.7.1.post6
python-json-logger==0.1.11
python-louvain==0.13
pytz==2019.2
pyxattr==0.6.0
pyxdg==0.25
PyYAML==3.12
pyzmq==18.0.2
raiss==0.1
requests==2.21.0
requests-oauthlib==1.2.0
requests-unixsocket==0.1.5
rpy2==3.2.0
rsa==4.0
scikit-learn==0.20.2
scipy==1.2.0
scour==0.36
seaborn==0.9.0
SecretStorage==2.3.1
service-identity==16.0.0
simplegeneric==0.8.1
simplejson==3.16.0
six==1.12.0
sortedcontainers==2.1.0
spectra==0.0.11
SQLAlchemy==1.3.8
ssh-import-id==5.7
statsmodels==0.9.0
system-service==0.3
systemd-python==234
tables==3.5.1
tabulate==0.8.3
tinycss2==0.6.1
toolz==0.10.0
tornado==6.0.3
tqdm==4.36.1
traitlets==4.3.2
Twisted==17.9.0
typing-extensions==3.7.4
tzlocal==2.0.0
ufw==0.36
umap==0.1.1
umap-learn==0.3.7
unattended-upgrades==0.1
urllib3==1.22
virtualenv==15.1.0
wcwidth==0.1.7
webencodings==0.5.1
wget==3.2
wrapt==1.11.2
xarray==0.13.0
xlrd==1.1.0
XlsxWriter==1.1.1
yarl==1.3.0
youtube-dl==2018.3.14
zipp==0.6.0
zope.interface==4.3.2
zstandard==0.12.0

Is it possible to lower the p-value threshold? And why when I prioritized a tissue with the following script, the results are in different tissues?

  bash
    
    studies=(Lifegen Zenin Evans90 Evans99)
    nstudies=${#studies[@]}
      
    tissues=(CELLS_EBV-TRANSFORMED_LYMPHOCYTES CELLS_TRANSFORMED_FIBROBLASTS COLON_SIGMOID COLON_TRANSVERSE ESOPHAGUS_GASTROESOPHAGEAL_JUNCTION ESOPHAGUS_MUCOSA ESOPHAGUS_MUSCULARIS HEART_ATRIAL_APPENDAGE HEART_LEFT_VENTRICLE CELLS_EBV-TRANSFORMED_LYMPHOCYTES CELLS_TRANSFORMED_FIBROBLASTS COLON_SIGMOID COLON_TRANSVERSE ESOPHAGUS_GASTROESOPHAGEAL_JUNCTION ESOPHAGUS_MUCOSA ESOPHAGUS_MUSCULARIS HEART_ATRIAL_APPENDAGE HEART_LEFT_VENTRICLE LIVER LUNG MINOR_SALIVARY_GLAND MUSCLE_SKELETAL NERVE_TIBIAL PANCREAS PITUITARY SKIN_NOT_SUN_EXPOSED_SUPRAPUBIC SKIN_SUN_EXPOSED_LOWER_LEG SMALL_INTESTINE_TERMINAL_ILEUM SPLEEN STOMACH THYROID WHOLE_BLOOD)
    ntissues=${#tissues[@]}
      
      cpt=0
      for idxstudy in `seq 0 $((nstudies - 1))`
        do
        study=${studies[$idxstudy]}
          for idxtissue in `seq 0 $((ntissues - 1))`
          do
          tissue=${tissues[$idxtissue]}
            for chr in {1..22}
            do
            cpt=$(($cpt+1))
            focus finemap /mnt/sde/pernic01/eQTL/GTEx/FOCUS/sum_stat_outcome_${study}_FOCUS_cleaned.sumstats.gz /home/pernic01/MendelD_pernic01/Nicolas/FOCUS/1000G_EUR_Phase3_plink/1000G.EUR.QC.${chr} /home/pernic01/MendelD_pernic01/Nicolas/FOCUS/focus.db --chr ${chr} --tissue ${tissue} --plot --out /mnt/sde/pernic01/eQTL/GTEx/FOCUS/results/Longevity_${study}.${tissue}.chr${chr} &
            if(( $cpt % 5 == 0 ));then wait;fi
          done
        done
      done
    

thanks

**Comment by jfertaj** [comment]
Hi @Nucholas,

Did you find the solution for the [ERROR]: 'symbol'?

Thanks

**Comment by Nucholas** [comment]
@jfertaj, I didn't find the solution.

@quattro, I'm trying using GTEx 8 data in FOCUS but when I import weights from predixcan pipeline (which I have compute on specific individuals) I have this error:

focus import GTEx8_Whole_Blood_HapMap_alpha0.5_window1e6_filtered.db predixcan --tissue Whole_Blood --name GTEx --assay rnaseq --output GTEx8

Starting log...
[2020-04-19 11:51:04 - INFO] Preparing weight database
[2020-04-19 11:51:09 - ERROR] (sqlite3.OperationalError) database is locked
[SQL: 
CREATE TABLE refpanel (
	id INTEGER NOT NULL, 
	ref_name VARCHAR(128) NOT NULL, 
	tissue VARCHAR(128) NOT NULL, 
	assay VARCHAR(128), 
	PRIMARY KEY (id)
)

]
(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/home/pernic01/.local/bin/focus", line 1279, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/pernic01/.local/bin/focus", line 1273, in main
    args.func(args)
  File "/home/pernic01/.local/bin/focus", line 996, in import_weights
    session.close()
UnboundLocalError: local variable 'session' referenced before assignment

**Comment by quattro** [comment]
Should be fixed due to #20 and #21
