### ISSUE TITLE
Using GTEx v8 Weight Databases

### ISSUE THREAD

**Issue by maegsul** [bogdanlab/focus#25]
Hi,

First of all, thank you @quattro for developing such useful and great tool! I am currently using FOCUS dev version (v0.7). I have 
two questions regarding the weight databases:

First, I am interested in creating custom weight databases that can be used for FOCUS for fine mapping the TWAS results (based on TWAS/fusion pipeline) I have generated using the same custom panels.

In addition to that, I also generated TWAS results using weights available at http://predictdb.org/ and usable by MetaXcan/PrediXcan pipeline. I know that FOCUS is compatible with PrediXcan weights as well, but in the wiki example I saw only GTEx v7 based analyses and not GTEx v8.

I created GTEx v8 based weight databases, and there were no problems for this neither. However, I used MASHR-based models but not Elastic Net models (as the authors recommend it), and when I check my FOCUS results output, I saw under the "inference" column that my MASHR-based model was still interpret as "ElasticNet". 

I wonder if this creates a bias for statistical testing, and I should avoid using MASHR-based models in FOCUS pipeline? Did you have any experience with this?

If possible, I'd like to use MASHR-based models as I have generated my original TWAS results using that. The output for the fine-mapped genes seems reasonable for me, but I just wanted to ask your opinion on this as well.

Second, I wonder if I should convert SNP IDs in the summary statistics file according to the variant naming of GTEx, such as in "chr1_100_A_T_b38" format, as actually these GTEx v8 models are using this format instead of rsIDs. I use GTEx name format for summary statistics that are used for PrediXcan/MetaXcan, but I am not sure if for FOCUS as well I should name the variants in this GTEx format as well.

Thank you in advance!

Edit: I tried having GTEx IDs vs rsIDs for the second question, and when GTEx IDs used FOCUS gave no output, indicating: "No overlap between LD reference and GWAS". So I assume FOCUS is only compatible with rsIDs (and if not available, CHR_POS_REF_ALT format, with "_b38" suffix?), even though GTEx weights did not have any rsIDs (so I assume these are converted during weight database preparation?).

**Comment by maegsul** [comment]
Thank you very much @quattro ! 

Indeed, my LD reference and GWAS summary statistics files are both manually annotated the same way, so they both contain rsIDs based on dbSNPv151 (GRCh38), and if there is no available corresponding rsID, they are annotated as "CHR_POS_REF_ALT".

However, as I indicated, PrediXcan GTEx v8 MASHR models (.db and .txt.gz files available at http://predictdb.org/) use chr1_100_A_T_b38 annotation system for the variants in the model, doesn't matter they have a corresponding rsID or not.  This is not the case for ElasticNet models that are using rsID annotations.

So I also tested providing a modified GWAS summary statistics to focus finemap where SNPs were annotated as chr1_100_A_T_b38 (the same one I use for running PrediXcan/MetaXcan for MASHR models), but it gave an error:

"_No overlap between LD reference and GWAS_"

I guess this is expected, as I still provide an LD reference data with rsID annotation (this file is not used for running PrediXcan/MetaXcan, as .txt.gz files are used for LD information). 

Anyway, I guess this might be sorted out at the weight database creation step somehow. I think the MASHR .db files contain both "rsid" and "varID" columns, where "varID" corresponds to the variant ID in the .txt.gz covariance file (used for running PrediXcan/MetaXcan only), and "rsid" column matches with the LD reference & summary statistics files provided in focus finemap step; so maybe that is why I did not see any problematic/weird FOCUS results in this scenario.

But of course if I interpret this wrong and I should be careful with this step, please do let me know! Thanks again!

**Comment by WeiCSong** [comment]
Hi,
   did your import step of GTEx v8 MASHR models create any error? I met the [ERROR] 'cv_R2_avg' constantly when running

`focus import $tissue predixcan --tissue $TISSUE --name GTEx --assay rnaseq --output gtex_v8`

I downloaded the same mashr model from http://predictdb.org/ and I would like to ask how did you import it into one .db file. Thanks!

**Comment by gg-n** [comment]
Hi @WeiCSong,

I am experiencing the same issue with [ERROR] 'cv_R2_avg', and also the other error too (ERROR] 'symbol') which you mention at another thread. May I ask if you have since managed to import GTEx v8 MASHR models and resolve the [ERROR] 'cv_R2_avg' issue? 

Any advice would be much appreciated! 

Thanks very much!!
GG

**Comment by WeiCSong** [comment]
> Hi @WeiCSong,
> 
> I am experiencing the same issue with [ERROR] 'cv_R2_avg', and also the other error too (ERROR] 'symbol') which you mention at another thread. May I ask if you have since managed to import GTEx v8 MASHR models and resolve the [ERROR] 'cv_R2_avg' issue?
> 
> Any advice would be much appreciated!
> 
> Thanks very much!!
> GG

Hi, 
I wrote an R script to manually concatenate all databases into the five data frames required by FOCUS, and wrote them to .db file. However, only the elastic net model worked fine using this script. Since my project needs robustness more than precision, i used this elasticnet.db and did not debug on mashr model. You may take a look at my [script](https://github.com/WeiCSong/antagSelection/blob/main/R/focus_import_alternative.R) and write a script to concatenate mashr model. The workflow is straightforward: update refpanel -> molecularfeature -> model -> modelattribute -> weight. You may also update the precise start and stop position of each gene in the molecularfeature data frame (I haven't done that since id did not impact the result).

**Comment by sookwah-yee** [comment]
Hi @WeiCSong @quattro,
I tried the focus import and try out one tissue from the GTEx v8 MASHR models, but I have error with mygene and rpy2? How do I installed mygene and rpy2? Any help?

===================================
              FOCUS v0.6.10            
===================================
focus import
	/mashr/mashr_Prostate.db
	predixcan
	--name GTEx
	--assay rnaseq
	--tissue Prostate
	--use-ens-id	--out /mashr/output/mashr_Prostate

Starting log...
[2021-11-27 08:27:33 - INFO] Preparing weight database
[2021-11-27 08:27:34 - ERROR] Import submodule requires mygene and rpy2 to be installed.
[2021-11-27 08:27:34 - ERROR] No module named 'mygene'
[2021-11-27 08:27:34 - INFO] Finished importing prediction models

**Comment by quattro** [comment]
Hi @sookwah-yee , you need to run `pip install mygene` and `pip install rpy2`. These aren't strict requirements for focus since the primary use case is fine-mapping, rather than importing new weights. We will update the error message to better reflect this.

**Comment by quattro** [comment]
Hi @sookwah-yee , can you try cloning the latest dev branch from the repo and installing that? It should be focus v 0.7.

**Comment by sookwah-yee** [comment]
Hi @quattro , it says that I have version 0.7, when I do "module show focus".  I don't know why the log for each run I did show up as 0.6. May I know what you mean by cloning the latest dev branch from the repo?  Where can I get it?  

module show focus # gives instructions for how to use
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
   /software/c4/wittelab/modulefiles/focus/0.7.0.lua:
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
help([[focus: a set of tools to finemap twas statistics 
]])
whatis("Version: 0.7.0")
whatis("Keywords: twas")
whatis("URL: https://github.com/bogdanlab/focus")
whatis("Description: FOCUS (Fine-mapping Of CaUsal gene Sets) is software to fine-map transcriptome-wide association study statistics at genomic risk regions. The software takes as input summary GW
AS data along with eQTL weights and outputs a credible set of genes to explain observed genomic risk. Example: source $ENV; focus --help; deactivate")
setenv("ENV","/software/c4/wittelab/software/focus-0.7.0/focus_venv/bin/activate")
prepend_path("PATH","/software/c4/wittelab/software/focus-0.7.0/bin")

**Comment by Mia1037** [comment]
Hi, @quattro,
I am creating custom weight databases , but I have error with'Series' object has no attribute 'DIR'. How can I fix it?
===================================
             FOCUS v0.802             
===================================
focus import
	/home/ubuntu/sln/GTExv8.ALL.Esophagus_Muscularis/GTExv8.ALL.Esophagus_Muscularis.pos
	fusion
	--tissue Muscularis
	--name Muscularis
	--assay rnaseq
	--output fusion

Starting log...
[2023-03-30 14:46:37 - INFO] Preparing weight database
[2023-03-30 14:46:37 - INFO] Starting import from FUSION database /home/ubuntu/sln/GTExv8.ALL.Esophagus_Muscularis/GTExv8.ALL.Esophagus_Muscularis.pos
[2023-03-30 14:46:37 - INFO] Querying mygene servers for gene annotations
[2023-03-30 14:46:58 - INFO] Starting individual model conversion
[2023-03-30 14:46:58 - ERROR] 'Series' object has no attribute 'DIR'
[2023-03-30 14:46:58 - INFO] Finished importing prediction models

**Comment by quattro** [comment]
We have not yet released a new DB, but the GTExv8 models for FUSION can be found here: http://gusevlab.org/projects/fusion/#gtex-v8-multi-tissue-expression
