### ISSUE TITLE
Default --n-min in munge

### ISSUE THREAD

**Issue by opain** [bogdanlab/focus#33]
Hello, 

In the munge help documentation it says the default -n-min value is '(90th percentile N) / **2**'. However, when I look at the default value used it says 'dat.N.quantile(0.9) / **1.5**'. Does this indicate the default value of --n-min is actually '(90th percentile N) / **1.5**'. 

Apologies if I am confused and thank you for your help.

Best wishes,

Ollie

**Comment by quattro** [comment]
Hi @opain , we will update the docs to reflect this! Thanks!

**Comment by opain** [comment]
Great!
