### ISSUE TITLE
FOCUS stalls on chromosome 6

### ISSUE THREAD

**Issue by m-wilke** [bogdanlab/focus#34]
First of all, thank you for a great tool!

Using the default p value, I have been able to fine map all chromosomes except for chromosome 6. It is getting stuck at region 6:30798168 - 6:31570931. From reading the Wiki, I know that the HLA region is not fine mapped by default, but I cannot think of another reason why the program is getting stuck on chromosome 6. Any troubleshooting advice would be very appreciated as it has been stuck on this chromosome for a few days.

#Focus finemap code
focus finemap sumstats.gz 1000G.EUR.QC.6 focus.db --chr 6  --out sumstats.chr6

Additionally, when using any p value less stringent than the default (i.e. a p<0.001 or p<0.01), chromosome 1 comes out with a .tsv file of zero output and an operational error is cited. I seem to have unlimited memory, CPU time and sqlite3 is the most updated version (as explained in https://github.com/bogdanlab/focus/issues/1), so I am not sure how I can remedy this. Has this been a problem you have seen before as chromosome 1 is the largest in terms of base pairs to run/fine map?

Thank you,
MacKenzie
sarvism@myumanitoba.ca

**Comment by gg-n** [comment]
Hi

Thank you for making this great tool available!

@MacKenzie, I have the same issue (using a p-threshold of 5e-6), it has been stuck at 6:30798168 - 6:31570931 for over 24h. May I ask if you have since managed to figure out the reason or find a solution? Any tips would be extremely helpful and appreciated.

Many thanks
GG

**Comment by m-wilke** [comment]
Hi @gg-n,

What I have done is I have removed the MHC/HLA region (the base pairs) from my GWAS summary statistic file and then re-ran FOCUS using the new summary statistics file. It seems as though the HLA region corresponds to where FOCUS is getting stuck. 

I still have not solved my issue with chromosome 1 but hopefully that helps for chromosome 6!

MacKenzie

**Comment by gg-n** [comment]
Hi @m-wilke,

Thanks very much for the useful tip. I have tried this now (as the MHC/HLA region is not my main target) and it has reduced the running time to 3h for chr6! Unfortunately I can't be much help with the chr1 issue, but hopefully others reading this thread might have some suggestions.

Many thanks
GG
