### ISSUE TITLE
Importing weights from FUSION 

### ISSUE THREAD

**Issue by biolyn** [bogdanlab/focus#35]
Hi,

I am trying to import FUSION weights to focus. The FUSION weights are directly downloaded from FUSION databases (http://gusevlab.org/projects/fusion/).

The directory test/ contains two files:
~/test$ ls
YFS.BLOOD.RNAARR       YFS.BLOOD.RNAARR.pos      YFS.BLOOD.RNAARR.profile.err
YFS.BLOOD.RNAARR.list    YFS.BLOOD.RNAARR.profile

"YFS.BLOOD.RNAARR" is a directory containing all .wgt.RDat weight files. YFS.BLOOD.RNAARR.pos is a file with weight lists: YFS.BLOOD.RNAARR/*****.wgt.RDat.

Under directory test/, I run:
focus import YFS.BLOOD.RNAARR.pos fusion --tissue blood --name GTEx --assay array --output YFS

There is always an error:

===================================
              FOCUS v0.7            
===================================
focus import
	YFS.BLOOD.RNAARR.pos
	fusion
	--tissue blood
	--name GTEx
	--assay array
	--output YFS

Starting log...
[2021-09-17 00:48:07 - INFO] Preparing weight database
[2021-09-17 00:48:07 - ERROR] import_fusion() missing 1 required positional argument: 'session'
[2021-09-17 00:48:07 - INFO] Finished importing prediction models

Any suggestions will be appreciated.
Thanks!
Sincerely,
lyn

**Comment by Priteshjain30** [comment]
Hi, 
I had the same issue while running this. For some reason it worked when I specified the original installation path of the focus script. 
For me it was installed in **/home/usr/.local/bin/**
Specifying this path somehow made the code run. Then I got an error to download 2 dependencies : mygene and rpy2, which were easily installed by pip. 

Hope this helps.
Pritesh

**Comment by biolyn** [comment]
Sorry for the late reply!
Thanks for your advice, and it does help me!
