### ISSUE TITLE
Tissue prioritization

### ISSUE THREAD

**Issue by rodrigoduarte88** [bogdanlab/focus#36]
Hi all! Thanks for this fantastic tool!

This is probably a stupid question, but here we go: when should we prioritize tissues with FOCUS (using the `--tissue` flag)?

Is it only when there's clear evidence of the involvement of a tissue? For example, in the FOCUS paper, the authors analyzed a GWAS of LDL levels and prioritized adipose tissue, which makes sense. However, could we prioritize tissues based on findings from the conditional analyses performed in FUSION? For example, if I ran a TWAS using all GTEx tissues, and I found some TWAS hits that were significant in the conditional analyses in 2-3 tissues, could I perform the FOCUS analysis by prioritizing one (or more) of these tissues?

**Comment by quattro** [comment]
Hi @rodrigoduarte88 , yes that is a reasonable approach. The `tissue` flag is still a bit of a heuristic in how it selects final inclusion of non-tissue models when they are missing from the specified tissue, but it should be a good step in the right direction.
