### ISSUE TITLE
How to train on individual-level data from reference panels

### ISSUE THREAD

**Issue by dzaccook** [bogdanlab/focus#4]
Hi,
I want to use focus in rice, can I train my data from the reference panels? 
Thank you!

**Comment by quattro** [comment]
I'm considering just dropping this feature for now. Looking at the code there are still some bugs, and the current implementation can't be distributed in an easy way for the FOCUS db.

I think the easier approach would be to use FUSION or PrediXcan to train, and then import after-the-fact.
