### ISSUE TITLE
Please specify independent regions location or default regions with '37:EUR', etc

### ISSUE THREAD

**Issue by corunesa** [bogdanlab/focus#44]
Hi!
I have this error and I do not know how to solve it. Could anybody help me?
Please specify independent regions location or default regions with '37:EUR', etc
Thanks in advance!

**Comment by quattro** [comment]
Hi @corunesa , we're working on fixing the default behavior, but for now please add `--locations 37:EUR` for GRCh37 EUR-based LD blocks. Please see `focus --help` for more information.

**Comment by corunesa** [comment]
Thank you very much! I had not found it but it is true that it is clarified in focus finemap --help.
Thanks again!
