### ISSUE TITLE
Integer column has NA values in column 3

### ISSUE THREAD

**Issue by Truman11Zeng** [bogdanlab/focus#45]
I had problems while I was running "focus finemap", and it looks like this:
===================================
             FOCUS v0.802
===================================
focus finemap
        ../Output/agnu_meta_Output_clean.trans_phar/agnu_meta_Output_clean.trans_phar_munge.sumstats.gz
        ../1000G_EUR_Phase3_plink/1000G.EUR.QC.11
        GTEx_Adipose_Visceral_Omentum.db
        --chr 11
        --tissue Adipose_Visceral_Omentum
        --p-threshold 1
        --out ../Output/agnu_meta_Output_clean.trans_phar/TWASresults/GTEx_Adipose_Visceral_Omentum/GTEx_Adipose_Visceral_Omentum.chr11

Starting log...
[2022-08-30 19:59:53 - INFO] Preparing GWAS summary file
[2022-08-30 20:00:24 - INFO] Preparing reference SNP data
[2022-08-30 20:00:24 - ERROR] Integer column has NA values in column 3
[2022-08-30 20:00:24 - INFO] Finished twas & fine-mapping

**Comment by quattro** [comment]
Hi @Truman11Zeng , please filter your input sumstat data to drop any values with NA/nan/inf or missing.

**Comment by corunesa** [comment]
Hi!
I had the same error and I do not have any NA or missing value

**Comment by quattro** [comment]
Hi @corunesa , can you update your version of pandas and re-run?

**Comment by corunesa85** [comment]
Thank you! Now it works!! :)
