### ISSUE TITLE
Focus import error - "500 Server Error: Internal Server Error for url: http://mygene.info/v3/query/"

### ISSUE THREAD

**Issue by rodrigoduarte88** [bogdanlab/focus#47]
Hi there

Has any of you seen this previously?

```
wget https://data.broadinstitute.org/alkesgroup/FUSION/WGT/NTR.BLOOD.RNAARR.tar.bz2
tar -xf NTR.BLOOD.RNAARR.tar.bz2
focus import NTR.BLOOD.RNAARR.pos fusion --tissue NTR_BLOOD --name NTR_BLOOD  --output NTR_BLOOD_focus_db

```
```
===================================
             FOCUS v0.802
===================================
focus import
        NTR.BLOOD.RNAARR.pos
        fusion
        --tissue NTR_BLOOD
        --name NTR_BLOOD
        --output DB_NAME

Starting log...
[2022-10-31 13:39:51 - INFO] Preparing weight database
[2022-10-31 13:39:51 - INFO] Starting import from FUSION database NTR.BLOOD.RNAARR.pos
[2022-10-31 13:39:51 - INFO] Querying mygene servers for gene annotations
[2022-10-31 13:39:52 - ERROR] 500 Server Error: Internal Server Error for url: http://mygene.info/v3/query/
[2022-10-31 13:39:52 - INFO] Finished importing prediction models
```

I am guessing it's a temporary error (fingers crossed), as I've used the exact same command previously to generate focus weights from fusion weights, and it would work normally, but today something's wrong.

**Comment by quattro** [comment]
Hi @rodrigoduarte88 , I haven't seen this before and looks like it could be an issue with mygene.py and/or mygene.info API changes. Be sure that your installed version of mygene is up to date using `pip` to see if it corrects the issue.

**Comment by rodrigoduarte88** [comment]
Hi @quattro, thanks for the prompt response. I think it was a temporary problem with the mygene servers, as I just re-tried this now, and it's back working. Thanks once more for this tool and for your help! :)
