### ISSUE TITLE
error in creating the weight database

### ISSUE THREAD

**Issue by ruthchia** [bogdanlab/focus#49]
Hi, I was trying to create the weight database using the CMC and GTEXv8 FUSION weights and encountered the error below. Although a `.db` file was created, I am not able to use the database that I created to run the finemapping portion of the analysis. Can you please offer guidance on this?

```
===================================
             FOCUS v0.802
===================================
focus import
	/data/ALS_50k/BrainBankSeq_May2021/MSA/Analysis.TWAS/fusion_twas/WEIGHTS/CMC.BRAIN.RNASEQ.pos
	fusion
	--tissue brain_dorsolateral_prefrontal_cortex
	--name CMC
	--assay rnaseq
	--output fusion

Starting log...
[2023-01-22 20:29:43 - INFO] Preparing weight database
[2023-01-22 20:29:43 - INFO] Starting import from FUSION database /data/ALS_50k/BrainBankSeq_May2021/MSA/Analysis.TWAS/fusion_twas/WEIGHTS/CMC.BRAIN.RNASEQ.pos
[2023-01-22 20:29:43 - INFO] Querying mygene servers for gene annotations
[2023-01-22 20:29:57 - INFO] Starting individual model conversion
[2023-01-22 20:29:57 - ERROR] 'Series' object has no attribute 'DIR'
[2023-01-22 20:29:57 - INFO] Finished importing prediction models
```

FYI, the FOCUS tool was installed in a container with the following pyfocus dependencies:
```
apt-get install -y python3-pip r-base
pip install numpy==1.23.1
pip install pyfocus mygene rpy2
```

I am guessing this error may have something to do with python packages/versions installed in the container. Can you tell me what specific versions are compatible with the current FOCUS tool?

thanks!
Ruth

**Comment by quattro** [comment]
Hi @ruthchia , please see the discussion in this thread: https://github.com/bogdanlab/focus/issues/40

Please let me know if that fixes the issue.

**Comment by ruthchia** [comment]
Hi @quattro, 
Brilliant! thanks for pointing me to the thread. 
The error is resolved!

Just one quick question: if my GWAS summary stats are of a different hg build from the weighted database, but my SNP IDs are in rsid format, do I still need to update the position to the same build as in the `.db` or would it just use the rsids for the analysis?

thanks!

**Comment by quattro** [comment]
Hi @ruthchia , rsIDs are used to align genetic data, so it should be fine if builds differ.
