### ISSUE TITLE
[WARNING] Unable to match ENSG00000228327.3 to Ensembl ID. Using ID for symbol

### ISSUE THREAD

**Issue by Mia1037** [bogdanlab/focus#53]
Hi,@quattro 
I was trying to import fusion wgt by focus import but had the following error for all my fusion genes, **show[ WARNING] Unable to match ENSG00000228327.3 to Ensembl ID. Using ID for symbol.**

And at the same time, when I used 1000G_Phase3_EAS_plinkfiles from Asians , I put in --locations 37:EAS  according to the information presented in  `focus --help`(specifying '37:EUR', '37:AFR', '37:EAS', '37:EUR-AFR', '37:EUR-EAS', '37:EAS-AFR', '37:EUR-EAS-A ) , show **[ERROR] Parsing LD blocks failed:[Errno 2] No such file or directory: '37:EAS'.**
Can you please tell me how I should resolve this? Here is my code

 thanks!

===================================
             FOCUS v0.802             
===================================
focus import
	/home/ubuntu/FUSION_WEIGHTS/GTExv8.ALL.Esophagus_Mucosa.pos
	fusion
	--tissue Mucosa
	--name Mucosa
	--assay rnaseq
	--use-ens-id
	--output fusion

[2023-03-30 20:01:51 - INFO] Preparing weight database
[2023-03-30 20:01:51 - INFO] Starting import from FUSION database /home/ubuntu/FUSION_WEIGHTS/GTExv8.ALL.Esophagus_Mucosa.pos
[2023-03-30 20:01:52 - INFO] Querying mygene servers for gene annotations
[2023-03-30 20:02:14 - INFO] Starting individual model conversion
[2023-03-30 20:02:14 - WARNING] Unable to match ENSG00000228327.3 to Ensembl ID. Using ID for symbol
[2023-03-30 20:02:14 - WARNING] Unable to match ENSG00000237491.8 to Ensembl ID. Using ID for symbol

/

===================================
             FOCUS v0.802             
===================================
focus finemap
        try_summary.cleaned.sumstats.gz
        /home/ubuntu/sln/FUSION_WEIGHTS/1000G.EAS.QC.1/1000G.EAS.QC.1
        focus.db
        --locations 37:EAS
        --out try_1

Starting log...
[2023-03-31 09:42:58 - INFO] Detecting 1 populations for fine-mapping.
[2023-03-31 09:42:58 - INFO] As a result, running single-population FOCUS.
[2023-03-31 09:42:58 - INFO] Preparing GWAS summary file for population at try_summary.cleaned.sumstats.gz.
[2023-03-31 09:43:13 - INFO] Preparing reference SNP data for population at /home/ubuntu/sln/FUSION_WEIGHTS/1000G.EAS.QC.1/1000G.EAS.QC.1.
[2023-03-31 09:43:14 - INFO] Preparing weight database at focus.db.
[2023-03-31 09:43:14 - INFO] Preparing user-defined locations at 37:EAS.
[2023-03-31 09:43:14 - ERROR] Parsing LD blocks failed:[Errno 2] No such file or directory: '37:EAS'
[2023-03-31 09:43:14 - INFO] Finished TWAS & fine-mapping. Thanks for using FOCUS, and have a nice day!

**Comment by quattro** [comment]
Hi, please try adding `--from-gencode` flag. This should prune the additional transcript version off the tail of the ensembl ID.

**Comment by XiaojingGu** [comment]
> Hi,@quattro I was trying to import fusion wgt by focus import but had the following error for all my fusion genes, **show[ WARNING] Unable to match ENSG00000228327.3 to Ensembl ID. Using ID for symbol.**
> 
> And at the same time, when I used 1000G_Phase3_EAS_plinkfiles from Asians , I put in --locations 37:EAS according to the information presented in `focus --help`(specifying '37:EUR', '37:AFR', '37:EAS', '37:EUR-AFR', '37:EUR-EAS', '37:EAS-AFR', '37:EUR-EAS-A ) , show **[ERROR] Parsing LD blocks failed:[Errno 2] No such file or directory: '37:EAS'.** Can you please tell me how I should resolve this? Here is my code
> 
> thanks!
> 
> # ===================================
> FOCUS v0.802
> focus import /home/ubuntu/FUSION_WEIGHTS/GTExv8.ALL.Esophagus_Mucosa.pos fusion --tissue Mucosa --name Mucosa --assay rnaseq --use-ens-id --output fusion
> 
> [2023-03-30 20:01:51 - INFO] Preparing weight database [2023-03-30 20:01:51 - INFO] Starting import from FUSION database /home/ubuntu/FUSION_WEIGHTS/GTExv8.ALL.Esophagus_Mucosa.pos [2023-03-30 20:01:52 - INFO] Querying mygene servers for gene annotations [2023-03-30 20:02:14 - INFO] Starting individual model conversion [2023-03-30 20:02:14 - WARNING] Unable to match ENSG00000228327.3 to Ensembl ID. Using ID for symbol [2023-03-30 20:02:14 - WARNING] Unable to match ENSG00000237491.8 to Ensembl ID. Using ID for symbol
> 
> /
> 
> # ===================================
> FOCUS v0.802
> focus finemap try_summary.cleaned.sumstats.gz /home/ubuntu/sln/FUSION_WEIGHTS/1000G.EAS.QC.1/1000G.EAS.QC.1 focus.db --locations 37:EAS --out try_1
> 
> Starting log... [2023-03-31 09:42:58 - INFO] Detecting 1 populations for fine-mapping. [2023-03-31 09:42:58 - INFO] As a result, running single-population FOCUS. [2023-03-31 09:42:58 - INFO] Preparing GWAS summary file for population at try_summary.cleaned.sumstats.gz. [2023-03-31 09:43:13 - INFO] Preparing reference SNP data for population at /home/ubuntu/sln/FUSION_WEIGHTS/1000G.EAS.QC.1/1000G.EAS.QC.1. [2023-03-31 09:43:14 - INFO] Preparing weight database at focus.db. [2023-03-31 09:43:14 - INFO] Preparing user-defined locations at 37:EAS. [2023-03-31 09:43:14 - ERROR] Parsing LD blocks failed:[Errno 2] No such file or directory: '37:EAS' [2023-03-31 09:43:14 - INFO] Finished TWAS & fine-mapping. Thanks for using FOCUS, and have a nice day!

Hi @Mia1037, I have the same error as:  [ERROR] Parsing LD blocks failed:[Errno 2] No such file or directory: '37:EAS'. Did you get it solved?
