### ISSUE TITLE
focus finemap error

### ISSUE THREAD

**Issue by guanjw8891** [bogdanlab/focus#59]
Very good job, but I have a question. An error was reported while I was doing the focus finemap calculation:
module 'numpy' has no attribute 'warning'. what is the reason for is?

**Comment by quattro** [comment]
Thanks for the report. Can you please include the version, and output from your analysis?

**Comment by guanjw8891** [comment]
$ cat log
cat: log: No such file or directory
[guanjiawei@Bioinformatics301 FOCUS_fine_mapping]$ cat focus_finemap_fusion_db.chr1.log 
===================================
             FOCUS v0.802             
===================================
focus finemap
	/HP_NL/PUBLIC/WORK/guanjiawei/analysis/TWAS_analysis/data/GWAS_summary/YanJian_han_tibetan/to_GRCh38/SL_Tibetan_EAS_3k_7k_liftover_GRCh38_focus.sumstats.gz
	/HP_NL/PUBLIC/WORK/guanjiawei/analysis/analysis_data/ref/ldsc/EAS_reference/1000G_Phase3_EAS_plinkfiles/1000G.EAS.QC.1
	/HP_NL/PUBLIC/WORK/guanjiawei/analysis/TWAS_analysis/analysis/pip_test/focus_weight_database/fusion.db
	--chr 1
	--out focus_finemap_fusion_db.chr1

Starting log...
[2023-06-21 22:11:12 - INFO] Preparing GWAS summary file
[2023-06-21 22:11:45 - INFO] Preparing reference SNP data
[2023-06-21 22:11:45 - ERROR] module 'numpy' has no attribute 'warnings'
[2023-06-21 22:11:45 - INFO] Finished twas & fine-mapping

I am very glad to receive your reply, I have another question wwhether numpy requires a special version

**Comment by guanjw8891** [comment]
The numpy version currently in use is 1.24.1
python version is 3.8.16

**Comment by quattro** [comment]
Thanks @guanjw8891 . It looks like the `numpy.warnings` module was removed from `numpy` in version `1.24`. It seems like it was just a reference to the builtin `warnings` module anyways, so this should be an easy fix. We'll get this patched soon.

**Comment by heomanism** [comment]
Hello, this error is not fixed until today. When are you planning to fix it?

**Comment by quattro** [comment]
This issue is fixed in latest version of [mancusolab/ma-focus](https://github.com/mancusolab/ma-focus)
